### ISSUE TITLE
Cannot switch base/counter asset on exchange

### ISSUE THREAD

**Issue by rarach** [Scopuly/scopuly#1]
When I go to https://scopuly.com/exchange and set XLM/SHX-Stronghold trading, the charts and orderbooks still show SHX/XLM (i.e. prices around 0.003).
I'd like to control base/counter assets - in this case to see prices around 280 SHX per XLM.

**Comment by Scopuly** [comment]
> Когда я захожу на https://scopuly.com/exchange и настраиваю торговлю XLM / SHX-Stronghold, графики и книги заказов по-прежнему показывают SHX / XLM (т.е. цены около 0,003).
> Я хотел бы контролировать базовые / встречные активы - в этом случае, чтобы увидеть цены около 280 SHX за XLM.



> When I go to https://scopuly.com/exchange and set XLM/SHX-Stronghold trading, the charts and orderbooks still show SHX/XLM (i.e. prices around 0.003).
> I'd like to control base/counter assets - in this case to see prices around 280 SHX per XLM.

**Comment by Scopuly** [comment]
> When I go to https://scopuly.com/exchange and set XLM/SHX-Stronghold trading, the charts and orderbooks still show SHX/XLM (i.e. prices around 0.003).
> I'd like to control base/counter assets - in this case to see prices around 280 SHX per XLM.

Thank you for finding the error. We have made changes and at the moment cross exchange pairs are working correctly, check.
